### ISSUE TITLE
ios 点播播放器播放视频，监听不到播放进度

### ISSUE THREAD

**Issue by lan2000** [LiteAVSDK/Player_Flutter#66]
```
super_player:
    git:
      url: https://github.com/tencentyun/SuperPlayer
      path: Flutter
      ref: release_pro_v10.7.0.13053_10.7.11936
```

superplayer_controller.dart 文件

_vodPlayEventListener = _vodPlayerController.onPlayerEventBroadcast.listen((event)

在ios端没有播放进度的回调，在安卓端就正常
