### ISSUE TITLE
引用这个包后,启动app会导致其他音频类app暂停播放

### ISSUE THREAD

**Issue by xiaohucode** [LiteAVSDK/Player_Flutter#82]
引用这个包后,启动app会导致其他音频类app暂停播放
比如用户正在喜马la雅听书,当打开我的app后会导致喜马la雅暂停播放

IOS平台
ios版本:15.6
使用的版本:
```  
super_player:
    git:
      url: https://github.com/LiteAVSDK/Player_Flutter
      ref: release_pro_v11.1.0
      path: Flutter
```
