### ISSUE TITLE
使用播放器后，屏幕亮度调节异常

### ISSUE THREAD

**Issue by lan2000** [LiteAVSDK/Player_Flutter#98]
播放器这个项目内部有一个亮度调节逻辑。启动APP后会注册屏幕亮度的广播接收器并设置窗口屏蔽亮度，这个会导致用户自己这边的业务受到影响，是否可以做成一个配置选项呢，允许用户关闭内部这个调节的功能？

**Comment by FZY456** [comment]
```
[√] Flutter (Channel stable, 3.13.8, on Microsoft Windows [版本 10.0.19042.630], locale zh-CN)
    • Flutter version 3.13.8 on channel stable at D:\flutter\flutter                          
    • Upstream repository https://github.com/flutter/flutter/                                 
    • FLUTTER_GIT_URL = https://github.com/flutter/flutter/                                   
    • Framework revision 6c4930c4ac (7 days ago), 2023-10-18 10:57:55 -0500                   
    • Engine revision 767d8c75e8                                                              
    • Dart version 3.1.4                                                                      
    • DevTools version 2.25.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Connected device (4 available)
    • WLZ AL10 (mobile) • FMLDU19C13016286 • android-arm64  • Android 12 (API 31)
```

华为nova6 ，harmonyos 3.0.0

**Comment by FZY456** [comment]
```
  super_player:
    git:
      url: https://github.com/tencentyun/SuperPlayer
      path: Flutter
      ref: release_pro_v11.3.0_13176_14333
```
